[tool.poetry]
name = "markblocks"
version = "0.1.0"
description = ""
authors = ["kfields <kurtisfields@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
sly = "^0.5"
Pygments = "^2.15.1"
emoji = "^2.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
